[package]
name = "cxx"
version = "1.0.68" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
rust-version = "1.48"
links = "cxxbridge1"
license = "MIT OR Apache-2.0"
description = "Safe interop between Rust and C++"
repository = "https://github.com/dtolnay/cxx"
documentation = "https://docs.rs/cxx"
homepage = "https://cxx.rs"
readme = "README.md"
exclude = ["/demo", "/gen", "/syntax", "/third-party"]
keywords = ["ffi"]
categories = ["development-tools::ffi", "api-bindings"]

[features]
default = ["std", "cxxbridge-flags/default"] # c++11
"c++14" = ["cxxbridge-flags/c++14"]
"c++17" = ["cxxbridge-flags/c++17"]
"c++20" = ["cxxbridge-flags/c++20"]
alloc = []
std = ["alloc"]

[dependencies]
cxxbridge-macro = { version = "=1.0.68", path = "macro" }
link-cplusplus = "1.0"

[build-dependencies]
cc = "1.0.49"
cxxbridge-flags = { version = "=1.0.68", path = "flags", default-features = false }

[dev-dependencies]
cxx-build = { version = "=1.0.68", path = "gen/build" }
cxx-gen = { version = "0.7", path = "gen/lib" }
cxx-test-suite = { version = "0", path = "tests/ffi" }
rustversion = "1.0"
trybuild = { version = "1.0.52", features = ["diff"] }

[workspace]
members = ["demo", "flags", "gen/build", "gen/cmd", "gen/lib", "macro", "tests/ffi"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "doc_cfg"]

[patch.crates-io]
cxx = { path = "." }
cxx-build = { path = "gen/build" }
