[package]
name = "cxxbridge-macro"
version = "1.0.105"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["development-tools::ffi"]
description = "Implementation detail of the `cxx` crate."
edition = "2021"
exclude = ["build.rs", "README.md"]
homepage = "https://cxx.rs"
keywords = ["ffi"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/cxx"
rust-version = "1.60"

[lib]
proc-macro = true

[features]
# incomplete features that are not covered by a compatibility guarantee:
experimental-async-fn = []
experimental-enum-variants-from-header = ["clang-ast", "flate2", "memmap", "serde", "serde_derive", "serde_json"]

[dependencies]
proc-macro2 = "1.0.63"
quote = "1.0.29"
syn = { version = "2.0.23", features = ["full"] }

# optional dependencies:
clang-ast = { version = "0.1.18", optional = true }
flate2 = { version = "1.0.26", optional = true }
memmap = { version = "0.7", optional = true }
serde = { version = "1.0.166", optional = true }
serde_derive = { version = "1.0.166", optional = true }
serde_json = { version = "1.0.100", optional = true }

[dev-dependencies]
cxx = { version = "1.0", path = ".." }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--generate-link-to-definition"]
