[package]
name = "cxxbridge-macro"
version = "0.1.2"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Implementation detail of the `cxx` crate."
repository = "https://github.com/dtolnay/cxx"

[lib]
proc-macro = true

[badges]
travis-ci = { repository = "dtolnay/cxx" }

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
cxx = { version = "0.1", path = ".." }
