[package]
name = "cxxbridge-macro"
version = "1.0.78"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["development-tools::ffi"]
description = "Implementation detail of the `cxx` crate."
edition = "2018"
exclude = ["build.rs", "README.md"]
homepage = "https://cxx.rs"
keywords = ["ffi"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/cxx"
rust-version = "1.48"

[lib]
proc-macro = true

[features]
# incomplete features that are not covered by a compatibility guarantee:
experimental-async-fn = []
experimental-enum-variants-from-header = ["clang-ast", "flate2", "memmap", "serde", "serde_json"]

[dependencies]
proc-macro2 = "1.0.39"
quote = "1.0.4"
syn = { version = "1.0.95", features = ["full"] }

# optional dependencies:
clang-ast = { version = "0.1", optional = true }
flate2 = { version = "1.0", optional = true }
memmap = { version = "0.7", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
cxx = { version = "1.0", path = ".." }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
