[package]
name = "cxxbridge-cmd"
version = "1.0.77"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["development-tools::build-utils", "development-tools::ffi"]
description = "C++ code generator for integrating `cxx` crate into a non-Cargo build."
edition = "2018"
exclude = ["build.rs"]
homepage = "https://cxx.rs"
keywords = ["ffi"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/cxx"
rust-version = "1.56"

[[bin]]
name = "cxxbridge"
path = "src/main.rs"

[features]
# incomplete features that are not covered by a compatibility guarantee:
experimental-async-fn = []

[dependencies]
clap = { version = "3.2", default-features = false, features = ["std", "suggestions"] }
codespan-reporting = "0.11"
proc-macro2 = { version = "1.0.39", default-features = false, features = ["span-locations"] }
quote = { version = "1.0", default-features = false }
syn = { version = "1.0.95", default-features = false, features = ["parsing", "printing", "clone-impls", "full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
