[package]
name = "cxxbridge-cmd"
version = "1.0.57"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
rust-version = "1.48"
license = "MIT OR Apache-2.0"
description = "C++ code generator for integrating `cxx` crate into a non-Cargo build."
repository = "https://github.com/dtolnay/cxx"
homepage = "https://cxx.rs"
exclude = ["build.rs"]
keywords = ["ffi"]
categories = ["development-tools::ffi"]

[[bin]]
name = "cxxbridge"
path = "src/main.rs"

[dependencies]
clap = "2.33"
codespan-reporting = "0.11"
proc-macro2 = { version = "1.0.26", default-features = false, features = ["span-locations"] }
quote = { version = "1.0", default-features = false }
syn = { version = "1.0.70", default-features = false, features = ["parsing", "printing", "clone-impls", "full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
